version: "3"
services:
  database:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: "paydb"
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "password"
      MARIADB_ROOT_USER: "root"
      MARIADB_ROOT_PASSWORD: "1234"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 1m
      timeout: 5s
      retries: 3

  gopangpayment:
    image: gopangpayment:0.0.1
    container_name: gopangpayment
    environment:
      PROFILE: "dev"
      DATABASESERVER_PORT: "3306"
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - backend

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      backend:
        aliases:
          - "zookeeper"
  kafkaserver:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper
    networks:
      backend:
        aliases:
          - "kafka"

networks:
  backend:
    driver: bridge